#!/usr/bin/env python3
"""Genera el reporte de costo en texto plano desde las cifras canónicas."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import datos

OUT = '/home/lilp/proyectos/reporte-costo-julio-2026.txt'
filas, T, tr = datos.calcular()
SEP = '═' * 47
L = []
w = L.append

w('*COSTO DE INVENTARIO — JULIO 2026*')
w('Piazza Pasticcio · venta 01–31/07/2026')
w('6 de 7 almacenes · SALUMERIA pendiente de reaplicación')
w('')
w(SEP)
w('')
w('*EL COSTO REAL DEL MES*')
w('')
w(f'Costo real de consumo              {T["pct_real"]:6.1f} %')
w(f'Costo teórico, por receta          {T["pct_teo"]:6.1f} %')
w(f'BRECHA                {T["pts"]:4.1f} pts · ${T["brecha"]:>10,.0f}')
w('')
w('El costo real es lo que *salió* del inventario:')
w('inventario inicial más compras, menos lo contado')
w(f'físicamente al cierre. ${T["neto"]:,.0f} sobre ${T["venta"]:,.0f}')
w('de venta atribuida. No depende de las recetas.')
w('')
w('El teórico es lo que las recetas dicen que *debió*')
w('salir por lo vendido. La diferencia es la brecha.')
w('')
w('*La venta atribuida no es la venta del mes.* El mes')
w(f'vendió ${datos.VENTA_POS:,.0f}. La venta atribuida suma')
w(f'${T["venta"]:,.0f}: es la venta de los productos que sí')
w('tienen receta, los únicos que consumen de un almacén.')
w(f'La diferencia de ${T["dif_venta"]:,.0f} son los ${datos.VENTA_SIN_RECETA:,.0f} de')
w('productos sin receta, que no descuentan de ningún')
w('inventario y por eso no se asignan a ninguno.')
w('')
w(SEP)
w('')
w('*DE DÓNDE SALE EL NÚMERO*')
w('')
w(f'Inventario inicial                    ${T["inicial"]:>10,.0f}')
w(f'Compras y transferencias recibidas    +{T["compras"]:>10,.0f}')
w(f'Inventario final contado              -{T["final"]:>10,.0f}')
w(f'Desperdicio registrado                -{datos.DESPERDICIO:>10,.0f}')
w(f'Consumo interno registrado            -{datos.CONSUMO_INTERNO:>10,.0f}')
w(f'Costo real, seis almacenes            ${T["real_bruto"]:>10,.0f}')
w(f'Transferencias entre almacenes        -{T["intra"]:>10,.0f}')
w(f'COSTO REAL CONSOLIDADO                ${T["neto"]:>10,.0f}')
w(f'Costo teórico                          {T["teorico"]:>10,.0f}')
w(f'BRECHA                                ${T["brecha"]:>10,.0f}')
w('')
w('Las transferencias se restan porque el mismo producto')
w('sale de un almacén y entra a otro: aparece como')
w('consumo del emisor y como entrada del receptor.')
w('')
w('Los seis almacenes cubren el mes completo, del 30/06')
w('al 31/07. COCINA y ALIMENTARI llegaron partidos en dos')
w('aplicaciones porque un inventario semanal quedó')
w('guardado como mensual y truncó su periodo mensual; se')
w('reconstruyeron desde saldos: inventario del 30/06 más')
w('compras de todo julio menos inventario del 31/07.')
w('')
w(SEP)
w('')
w('*POR ALMACÉN*')
w('')
w('```')
w(f'{"":11}{"real neto":>10}{"%":>7}{"teórico":>10}{"brecha":>10}')
for f in filas:
    pr = f'{f["pct_real"]:7.1f}' if f['pct_real'] else '    n/a'
    w(f'{f["alm"]:<11}{f["neto"]:>10,.0f}{pr}{f["teorico"]:>10,.0f}{f["brecha"]:>10,.0f}')
w(f'{"TOTAL":<11}{T["neto"]:>10,.0f}{T["pct_real"]:>7.1f}{T["teorico"]:>10,.0f}{T["brecha"]:>10,.0f}')
w('```')
w('')
w('GENERAL no vende: es almacén de distribución, su')
w('porcentaje no es food cost y no se calcula.')
w('AMICI al 94 % es artefacto de denominador —su almacén')
w('recibe $81,238 de los $217,272 vendidos en sus')
w('ambientes—; normalizado corre a ~35 %.')
w('')
w(SEP)
w('')
w('*ROTACIÓN*')
w('')
w('```')
w(f'{"":11}{"inv. final":>11}{"días":>7}{"rot/año":>9}')
for f in filas:
    w(f'{f["alm"]:<11}{f["final"]:>11,.0f}{f["dias_inv"]:>7.0f}{f["rot"]:>9.1f}')
w(f'{"TOTAL":<11}{T["final"]:>11,.0f}{T["dias_inv"]:>7.0f}{T["rot"]:>9.1f}')
w('```')
w('')
w(f'Cada día de inventario son ${T["capital_dia"]:,.0f} de producto')
w('en piso. ALIMENTARI es el capital más inmovilizado:')
w(f'${[f for f in filas if f["alm"]=="ALIMENTARI"][0]["final"]:,.0f} con {[f for f in filas if f["alm"]=="ALIMENTARI"][0]["rot"]:.1f} rotaciones al año.')
w('')
w(SEP)
w('')
w('*COMPOSICIÓN DE LA BRECHA*')
w('')
cocina = [f for f in filas if f['alm'] == 'COCINA'][0]
w(f'*1 · COCINA — ${cocina["brecha"]:,.0f}*')
w(f'El {cocina["brecha"]/T["brecha"]*100:.0f} % de la brecha del mes. Es también el almacén')
w('con menor cobertura de conteo del sistema: 69 códigos')
w('contados de 742. Sus mayores faltantes son insumos de')
w('alto costo que se porcionan —trufa $7,735, leche')
w('bronca $7,450, mantequilla $6,499, wagyu $6,085—,')
w('donde la receta descuenta menos de lo que se usa.')
w('')
w('*2 · Productos sin receta — ~$79,450 de costo*')
w(f'73 productos vendieron ${datos.VENTA_SIN_RECETA:,.0f} con costo')
w('asociado $0.00. Los 10 primeros concentran $213,682.')
w('Costo estimado al 25.39 %, la razón de los costeados.')
w('154 platos de spaghettoni salieron sin que se')
w('descontara un gramo de pasta.')
w('')
w('*3 · GENERAL — $36,417 · conteo no realizado*')
w('Salieron $173,534 y $131,511 están trazados como')
w('transferencia, con origen, destino, encargado y fecha.')
w('Del residuo, $25,535 —el 79 %— sale de 59 códigos con')
w('movimiento que se contaron en CERO: bolsas de alto')
w('vacío, contenedores de paja, celofán, corcho, botella')
w('bordalesa. Del grupo EMPAQUE, 6 de 86 códigos')
w('recibieron conteo.')
w('')
w('De agosto no se cuentan desechables ni suministros.')
w('Para que la partida cierre deben salir del inventario')
w('valorizado —gasto directo en la compra— *y* de las')
w('recetas. Si permanecen sin conteo, su compra íntegra')
w('se convierte en variación cada mes. Hecho completo, la')
w(f'brecha baja a ~${T["brecha"]-12994:,.0f}.')
w('')
w('*4 · Recetas que descuentan de menos — $51,333*')
w('135 artículos: harina 75 kg usados contra 20')
w('descontados, aceite de oliva 18.9 contra 4.7, pollo')
w('orgánico 23.0 contra 8.5. Medido sobre una semana, la')
w('cifra mensual será mayor.')
w('')
w('*5 · Merma y consumo interno — $174 registrados*')
w('Dos registros en todo el mes. A 1.5 % de venta lo')
w('esperable ronda $35,000. El almacén COMIDA PERSONAL')
w('entrega producto por transferencia en vez de')
w('registrarlo como consumo interno.')
w('')
w('*6 · CAVA — $34,442 sin causa identificada*')
w('No transforma producto ni prepara mezclas: ninguna de')
w('las causas anteriores aplica. 12 artículos con receta')
w('activa salieron sin venta asociada, $17,994.')
w('')
w(SEP)
w('')
w('*EL DISEÑO DEL MENÚ*')
w('')
w('El menú está construido para correr a *25.4 %*,')
w('medido producto por producto en el punto de venta')
w('sobre los 409 con receta cargada. Coincide con el')
w(f'{T["pct_teo"]:.1f} % teórico de los almacenes: dos mediciones')
w('independientes que se validan entre sí.')
w('')
w('Dividir el costo registrado ($515,683) entre la venta')
w('total da 22.0 %, resultado bajo porque 73 productos')
w('—el 13.3 % de la venta— tienen costo cero. Ambos son')
w(f'teóricos. El consumo medido es {T["pct_real"]:.1f} %.')
w('')
w(SEP)
w('')
w('*ACCIONES, POR RETORNO*')
w('')
w(f'1. Auditar COCINA — ${cocina["brecha"]:,.0f}, el {cocina["brecha"]/T["brecha"]*100:.0f} % del total,')
w('   con 69 códigos contados de 742.')
w('2. Cargar receta a los 73 productos sin costeo')
w('   — ~$79,450. Es una lista, está en el Excel.')
w(f'3. Reaplicar SALUMERIA — ${datos.SALUMERIA["brecha"]:,.0f}. Auditar primero')
w('   el cerdo en canal, 70 % de su brecha.')
w('4. Recalibrar las 135 recetas — $51,333.')
w('5. Auditar CAVA — $34,442.')
w('6. Capturar merma y consumo interno — ~$35,000.')
w('7. Sacar desechables del valorizado — $12,994.')
w('')
w(SEP)
w('')
w('*ALCANCE*')
w('')
w('SALUMERIA no está en ninguna cifra: su corte quedó')
w(f'anulado. Aportaría ${datos.SALUMERIA["brecha"]:,.0f}, llevando la brecha a')
w(f'~${T["brecha_con_salumeria"]:,.0f}.')
w('')
w('No es una conciliación contable definitiva. La única')
w('cifra estimada es el costo de los productos sin')
w('receta; el resto viene directo de Xetux.')
w('')
w(f'Trazabilidad: {T["movimientos"]} transferencias por ${T["transf_total"]:,.0f},')
w('todas con origen, destino, encargado y fecha.')

open(OUT, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
print(f'{os.path.basename(OUT)}  {os.path.getsize(OUT)/1024:.1f} KB  ·  {len(L)} líneas')
